<a href="https://colab.research.google.com/github/brenoSilva292/proUni_2020_DataScience/blob/main/Prouni_2020.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Prouni - 2020
O Programa Universidade para Todos - Prouni tem como finalidade a concessão de bolsas de estudo integrais e parciais em cursos de graduação e sequenciais de formação específica, em instituições de ensino superior privadas que oferece, em contrapartida, isenção de tributos àquelas instituições que aderem ao Programa.Dirigido aos estudantes egressos do ensino médio da rede pública ou da rede particular na condição de bolsistas integrais, com renda familiar per capita máxima de três salários mínimos, o Prouni conta com um sistema de seleção informatizado e impessoal, que confere transparência e segurança ao processo. Os candidatos são selecionados pelas notas obtidas no **Exame Nacional do Ensino Médio - Enem** conjugando-se, desse modo, inclusão à qualidade e mérito dos estudantes com melhores desempenhos acadêmicos.

In [ ]:
# importar os pacote necessários
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Diz:mostre os gráficos diretamente dentro da célula
%matplotlib inline

In [ ]:
# importar o arquivo para um DataFrame
df = pd.read_csv("/content/sample_data/ProuniRelatorioDadosAbertos2020.csv",
                 encoding='latin1',
                 sep=';')


Conjunto de dados: Bolsas concedidas e perfil dos beneficiários do Prouni

# Dicionário das variáveis

- `ANO_CONCESSAO_BOLSA` - Ano da concessão da bolsa.
- `CODIGO_EMEC_IES_BOLSA` - Código do e-MEC da IES que concedeu a bolsa.
- `NOME_IES_BOLSA` - Nome/Razão Social da Instituição de Ensino Superior que concedeu a bolsa ProUni.
- `TIPO_BOLSA` - Descrição do tipo da bolsa concedida ao beneficiário do ProUni (integral – 100% ou parcial – 50%).
- `MODALIDADE_ENSINO_BOLSA` - Modalidade de ensino (presencial ou ensino à distância – EAD).
- `NOME_CURSO_BOLSA` - Nome do curso.
- `NOME_TURNO_CURSO_BOLSA` - Turno do curso.
- `CPF_BENEFICIARIO_BOLSA` - CPF do beneficiário.

## Detalhamento do perfil dos beneficiários do Prouni por:

- `SEXO_BENEFICIARIO_BOLSA` - Sexo do beneficiário.
- `RACA_BENEFICIARIO_BOLSA` - Raça/cor.
- `DT_NASCIMENTO_BENEFICIARIO` - Data de nascimento do beneficiário.
- `BENEFICIARIO_DEFICICIENTE_FISICO` - Indicação se o beneficiário é portador de deficiência.
- `REGIAO_BENEFICIARIO_BOLSA` - Região.
- `SIGLA_UF_BENEFICIARIO_BOLSA`- UF.
- `MUNICIPIO_BENEFICIARIO_BOLSA` - Município.

In [ ]:
# Mostrar as 5 primeiras entradas
df.head()

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,MUNICIPIO,CAMPUS,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO,SEXO_BENEFICIARIO,RACA_BENEFICIARIO,DATA_NASCIMENTO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO,UF_BENEFICIARIO,MUNICIPIO_BENEFICIARIO
0,2020,322,UNIVERSIDADE PAULISTA,IPATINGA,IPATINGA,INTEGRAL,EAD,PEDAGOGIA,CURSO A DISTÂNCIA,991.XXX.XXX-91,F,Parda,11/08/1973,N,SUDESTE,MG,GOVERNADOR VALADARES
1,2020,163,UNIVERSIDADE ESTÁCIO DE SÁ,FORTALEZA,EAD VIA CORPVS - CE,INTEGRAL,EAD,MARKETING,CURSO A DISTÂNCIA,067.XXX.XXX-01,M,Parda,13/05/1987,N,NORDESTE,CE,FORTALEZA
2,2020,17670,FACULDADE DE QUIXERAMOBIM,QUIXERAMOBIM,FACULDADE DE QUIXERAMOBIM - UNIQ,INTEGRAL,PRESENCIAL,FARMÁCIA,NOTURNO,623.XXX.XXX-27,M,Parda,23/07/2001,N,NORDESTE,CE,MOMBACA
3,2020,203,UNIVERSIDADE SÃO JUDAS TADEU,SAO PAULO,PAULISTA,PARCIAL,PRESENCIAL,DIREITO,MATUTINO,089.XXX.XXX-40,F,Branca,04/04/2003,N,NORDESTE,BA,IBITITA
4,2020,203,UNIVERSIDADE SÃO JUDAS TADEU,SAO PAULO,PAULISTA,INTEGRAL,PRESENCIAL,DIREITO,MATUTINO,173.XXX.XXX-09,F,Branca,07/12/1977,N,SUDESTE,SP,SAO PAULO

In [ ]:
# Identificar o volume de dados do DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166830 entries, 0 to 166829
Data columns (total 17 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ANO_CONCESSAO_BOLSA             166830 non-null  int64
 1   CODIGO_EMEC_IES_BOLSA           166830 non-null  int64
 2   NOME_IES_BOLSA                  166830 non-null  object
 3   MUNICIPIO                       166830 non-null  object
 4   CAMPUS                          166830 non-null  object
 5   TIPO_BOLSA                      166830 non-null  object
 6   MODALIDADE_ENSINO_BOLSA         166830 non-null  object
 7   NOME_CURSO_BOLSA                166792 non-null  object
 8   NOME_TURNO_CURSO_BOLSA          166830 non-null  object
 9   CPF_BENEFICIARIO                166830 non-null  object
 10  SEXO_BENEFICIARIO               166830 non-null  object
 11  RACA_BENEFICIARIO               166830 non-null  object
 12  DATA_NASCIMENTO                 166830 non-null  object
 13  BENEFICIARIO_DEFICIENTE_FISICO  166830 non-null  object
 14  REGIAO_BENEFICIARIO             166830 non-null  object
 15  UF_BENEFICIARIO                 166830 non-null  object
 16  MUNICIPIO_BENEFICIARIO          166830 non-null  object
dtypes: int64(2), object(15)
memory usage: 21.6+ MB

In [ ]:
# verificar as 5 primeiras entradas do dataset
df.head()

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,MUNICIPIO,CAMPUS,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO,SEXO_BENEFICIARIO,RACA_BENEFICIARIO,DATA_NASCIMENTO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO,UF_BENEFICIARIO,MUNICIPIO_BENEFICIARIO
0,2020,322,UNIVERSIDADE PAULISTA,IPATINGA,IPATINGA,INTEGRAL,EAD,PEDAGOGIA,CURSO A DISTÂNCIA,991.XXX.XXX-91,F,Parda,11/08/1973,N,SUDESTE,MG,GOVERNADOR VALADARES
1,2020,163,UNIVERSIDADE ESTÁCIO DE SÁ,FORTALEZA,EAD VIA CORPVS - CE,INTEGRAL,EAD,MARKETING,CURSO A DISTÂNCIA,067.XXX.XXX-01,M,Parda,13/05/1987,N,NORDESTE,CE,FORTALEZA
2,2020,17670,FACULDADE DE QUIXERAMOBIM,QUIXERAMOBIM,FACULDADE DE QUIXERAMOBIM - UNIQ,INTEGRAL,PRESENCIAL,FARMÁCIA,NOTURNO,623.XXX.XXX-27,M,Parda,23/07/2001,N,NORDESTE,CE,MOMBACA
3,2020,203,UNIVERSIDADE SÃO JUDAS TADEU,SAO PAULO,PAULISTA,PARCIAL,PRESENCIAL,DIREITO,MATUTINO,089.XXX.XXX-40,F,Branca,04/04/2003,N,NORDESTE,BA,IBITITA
4,2020,203,UNIVERSIDADE SÃO JUDAS TADEU,SAO PAULO,PAULISTA,INTEGRAL,PRESENCIAL,DIREITO,MATUTINO,173.XXX.XXX-09,F,Branca,07/12/1977,N,SUDESTE,SP,SAO PAULO